FROM ubuntu:22.04 AS builder

RUN apt-get update \
&& DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
    build-essential autoconf bison flex texinfo \
    help2man gawk libtool libtool-bin libtool-doc libncurses5-dev python3-dev \
    python3-distutils git unzip wget curl ca-certificates

ARG BUILD_ARCH=unknown
ARG CPU_COUNT=1
ARG CROSSTOOL_VER=1.27.0

WORKDIR /opt

RUN useradd build && chown build:build /opt

USER build

RUN wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-${CROSSTOOL_VER}.tar.xz && tar -xf crosstool-ng-${CROSSTOOL_VER}.tar.xz

WORKDIR /opt/crosstool-ng-${CROSSTOOL_VER}

RUN ./configure --enable-local && make

RUN 

COPY files/config_${BUILD_ARCH} /opt/crosstool-ng-${CROSSTOOL_VER}/.config

RUN ./ct-ng build

USER root

RUN mkdir /done; cd /opt/x-tools/*; tar -zcf /done/${BUILD_ARCH}-ulibc-toolchain.tar.gz .

FROM scratch AS artifact
COPY --from=builder /done /done