name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Do AARCH64 Build 
        run: ./build_musl.sh aarch64-linux-musl
      - name: Do AARCH64BE Build 
        run: ./build_musl.sh aarch64_be-linux-musl
      - uses: actions/upload-artifact@v4
        with:
          name: build_tars
          path: "*.tar.gz"
      - name: Release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: "*.tar.gz"
          name: "Latest"
          allowUpdates: true
          tag: latest