name: Build ARM
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Do ARM Build 
        run: ./build_musl.sh arm-linux-musleabi
      - name: Do ARMeb Build 
        run: ./build_musl.sh armeb-linux-musleabi
      - name: Do ARMel Build 
        run: ./build_musl.sh armel-linux-musleabi
      - uses: actions/upload-artifact@v4
        with:
          name: build_tars
          path: "done/*.tar.gz"
      - name: Release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: "done/*.tar.gz"
          name: "Latest"
          allowUpdates: true
          tag: latest