name: Build ARM
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Do ARM Build 
        run: ./build_musl.sh arm-linux-musleabi
      - name: Do ARMv7l Build 
        run: ./build_musl.sh armv7l-linux-musleabihf
      - name: Do ARMv7m Build 
        run: ./build_musl.sh armv7m-linux-musleabi
      - uses: actions/upload-artifact@v4
        with:
          name: build_tars
          path: "*.tar.gz"
      - name: Release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: "*.tar.gz"
          name: "Latest"
          allowUpdates: true
          tag: latest