name: Build MIPS
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Do MIPS Build 
        run: ./build_musl.sh mips-linux-musl
      - name: Do MIPSn32sf Build 
        run: ./build_musl.sh mips-linux-musln32sf
      - name: Do MIPS64 Build 
        run: ./build_musl.sh mips64-linux-musl
      - uses: actions/upload-artifact@v4
        with:
          name: build_tars
          path: "done/*.tar.gz"
      - name: Release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: "done/*.tar.gz"
          name: "Latest"
          allowUpdates: true
          tag: latest