name: Build Other Architectures
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Do Motorola 680x0 Build 
        run: ./build_musl.sh m68k-linux-musl
      - name: Do SuperH 4 Build 
        run: ./build_musl.sh sh4-linux-musl
      - name: Do SuperH 4 BE Build 
        run: ./build_musl.sh sh4eb-linux-musl
      - name: Do SystemZ Build 
        run: ./build_musl.sh s390x-linux-musl
      - uses: actions/upload-artifact@v4
        with:
          name: build_tars
          path: "done/*.tar.gz"
      - name: Release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: "done/*.tar.gz"
          name: "Latest"
          allowUpdates: true
          tag: latest