name: Build ARM
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Do PowerPC Build 
        run: ./build_musl.sh powerpc-linux-musl
      - name: Do PowerPC64 Build 
        run: ./build_musl.sh powerpc64-linux-musl
      - name: Do PowerPCle Build 
        run: ./build_musl.sh powerpcle-linux-musl
      - name: Do PowerPCle-sf Build 
        run: ./build_musl.sh powerpcle-linux-muslsf
      - uses: actions/upload-artifact@v4
        with:
          name: build_tars
          path: "done/*.tar.gz"
      - name: Release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: "done/*.tar.gz"
          name: "Latest"
          allowUpdates: true
          tag: latest